django_project/vimanam/airplanes/urls.py
from django.urls import path
from . import views

app_name = "airplanes"

urlpatterns = [
    path(r"d/", views.get_context_data, name="getContextData"),
    path(r"d/<str:reg_num>/", views.get_airplane_data, name="getAirplaneData"),
]

django_project/vimanam/home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path(r"", views.get_context_data, name="getContextData"),
]

django_project/vimanam/models/urls.py
from django.urls import path
from . import views

app_name = "models"

urlpatterns = [
    path(r"d/", views.get_context_data, name="getContextData"),
    path(r"d/<str:model_num>/", views.get_model_data, name="getModelData"),
]

django_project/vimanam/technicians/urls.py
from django.urls import path
from . import views

app_name = "technicians"

urlpatterns = [
    path(r"d/", views.get_context_data, name="getContextData"),
    path(r"d/<str:ssn>/", views.get_technician_data, name="getTechnicianData"),
]

django_project/vimanam/vimanam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls","home")),
    path('airplanes/', include("airplanes.urls","airplanes")),
    path('models/', include("models.urls","models")),
    path('technicians/', include("technicians.urls","technicians")),
    path('tests/', include("tests.urls","tests")),
    path('__reload__/',include("django_browser_reload.urls")),
]

django_project/vimanam/airplanes/models.py
from django.db import models

# Create your models here.

django_project/vimanam/home/models.py
from django.db import models

# Create your models here.

django_project/vimanam/models/admin.py
from django.contrib import admin

# Register your models here.

django_project/vimanam/models/apps.py
from django.apps import AppConfig


class ModelsConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'models'

django_project/vimanam/models/models.py
from django.db import models

# Create your models here.

django_project/vimanam/models/tests.py
from django.test import TestCase

# Create your tests here.

django_project/vimanam/models/views.py
from django.shortcuts import render
from django.http import HttpResponse
import oracledb


# Create your views here.
def get_context_data(request):
    conn = oracledb.connect(
        user="system",
        password="anish",
        host="localhost",
        port="1521",
        service_name="XE"
    )

    curr = conn.cursor()
    
    if request.method == "GET":
        search_param = request.GET.get('s', None)
        field_param = request.GET.get('f', None)

        if search_param is not None:
            fields_map = {
                '1':"model_num",
                '2':"capacity",
                '3':"weight"
            }

            search_query = f"SELECT * FROM models WHERE {fields_map[field_param]} LIKE '%{search_param}%'"
            data = curr.execute(search_query)
        else:
            gen_query = "SELECT * FROM models"
            data = curr.execute(gen_query)

        context = []

        for record in data:
            context_item = {
                "model_num":record[0],
                "capacity":record[1],
                "weight":record[2],
            }
            context.append(context_item)

    return render(request, 'models.html', {"context":context})

def get_model_data(request, model_num):
    conn = oracledb.connect(
        user="system",
        password="anish",
        host="localhost",
        port="1521",
        service_name="XE"
    )

    curr = conn.cursor()
    print(model_num)
    query = f"SELECT * FROM models WHERE model_num = '{model_num}'"
    print(query)
    result = curr.execute(query)

    for record in result:
        model_details = {
            "model_num":record[0],
            "capacity":record[1],
            "weight":record[2],
        }

    airplanes_query = f"""
        SELECT registration_num, airline
        FROM airplanes
        WHERE model_num = '{model_details["model_num"]}'
    """

    result = curr.execute(airplanes_query)

    airplane_details = []
    counter = 1
    for record in result:
        airplane_item = {
            "serial_num": counter,
            "registration_num": record[0],
            "airline": record[1]
        }
        counter += 1
        airplane_details.append(airplane_item)

    technicians_query = f"""
        SELECT first_name, last_name, ssn
        FROM technicians
        WHERE ssn IN (
            SELECT ssn
            FROM expertise
            WHERE model_num = '{model_details["model_num"]}'
        )
    """

    result = curr.execute(technicians_query)

    technicians_details = []
    for record in result:
        technicians_item = {
            "first_name": record[0],
            "last_name": record[1],
            "ssn": record[2]
        }
        technicians_details.append(technicians_item)

    context = {
        "model_details":model_details,
        "airplane_details": airplane_details,
        "technicians_details": technicians_details
    }

    return render(request, 'modelProfile.html', {"context": context})    

    

django_project/vimanam/technicians/models.py
from django.db import models

# Create your models here.

django_project/vimanam/airplanes/views.py
from django.shortcuts import render
from django.http import HttpResponse
import oracledb


# Create your views here.
def get_context_data(request):
    conn = oracledb.connect(
        user="system",
        password="anish",
        host="localhost",
        port="1521",
        service_name="XE"
    )

    curr = conn.cursor()
    
    if request.method == "GET":
        search_param = request.GET.get('s', None)
        field_param = request.GET.get('f', None)

        if search_param is not None:
            fields_map = {
                '1':"registration_num",
                '2':"model_num",
                '3':"airline"
            }

            search_query = f"SELECT * FROM airplanes WHERE {fields_map[field_param]} LIKE '%{search_param}%'"
            data = curr.execute(search_query)
        else:
            gen_query = "SELECT * FROM airplanes"
            data = curr.execute(gen_query)

        context = []

        for record in data:
            context_item = {
                "registration_num":record[0],
                "model_num":record[1],
                "airline":record[2],
            }
            context.append(context_item)

    return render(request, 'airplanes.html', {"context":context})

def get_airplane_data(request, reg_num):
    conn = oracledb.connect(
        user="system",
        password="anish",
        host="localhost",
        port="1521",
        service_name="XE"
    )

    print(reg_num)

    curr = conn.cursor()

    query = f"SELECT * FROM airplanes WHERE registration_num = {reg_num}"

    result = curr.execute(query)

    context = None

    for record in result:
        airplane_details = {
            "registration_num":record[0],
            "model_num":record[1],
            "airline":record[2],
        }

    tests_query = f"""
        SELECT * FROM tests
        WHERE registration_num = {reg_num}
        ORDER BY test_date DESC
    """

    result = curr.execute(tests_query)

    tests_details = []

    counter = 1
    for record in result:
        test_item = {
            "serial_num": counter,
            "test_num":record[0],
            "test_name":record[1],
            "ssn":record[2],
            "registration_num": record[3],
            "test_date": record[4].date().__str__(),
            "maximum_score": record[5],
            "number_of_hours": record[6],
            "airplane_score": record[7],
        }
        tests_details.append(test_item)
        counter += 1

    model_query = f"""
        SELECT models.model_num, models.capacity, models.weight
        FROM models
        WHERE model_num = (
            SELECT model_num FROM airplanes
            WHERE registration_num = {reg_num}
        )
    """ 

    result = curr.execute(model_query)

    for record in result:
        model_details = {
                "model_num":record[0],
                "capacity":record[1],
                "weight":record[2],
        }

    
    technician_query = f"""
        SELECT ssn, first_name, last_name
        FROM technicians
        WHERE ssn IN (
            SELECT ssn 
            FROM expertise
            WHERE model_num = '{model_details["model_num"]}'
        )
    """
    result = curr.execute(technician_query)

    technicians_details = []

    for record in result:
        technician_item = {
            "ssn": record[0],
            "first_name":record[1],
            "last_name":record[2],
        }
        technicians_details.append(technician_item)

    print(technicians_details)
    
    context = {
        "airplane_details":airplane_details,
        "tests_details":tests_details,
        "model_details": model_details,
        "technicians_details": technicians_details
    }




    return render(request, 'airplaneProfile.html', {"context": context})    

    

django_project/vimanam/home/views.py
from django.shortcuts import render

# Create your views here.
def get_context_data(request):
    return render(request, 'home.html')

django_project/vimanam/technicians/views.py
from django.shortcuts import render
from django.http import HttpResponse
import oracledb


# Create your views here.
def get_context_data(request):
    conn = oracledb.connect(
        user="system",
        password="anish",
        host="localhost",
        port="1521",
        service_name="XE"
    )

    curr = conn.cursor()
    
    if request.method == "GET":
        search_param = request.GET.get('s', None)
        field_param = request.GET.get('f', None)

        if search_param is not None:
            fields_map = {
                '1':"ssn",
                '2':"first_name",
                '3':"last_name",
                '4':"gender",
                '5':"phone_num",
                '6':"street_address",
                '7':"city",
                '8':"country",
                '9':"salary"
            }

            search_query = f"SELECT * FROM technicians WHERE {fields_map[field_param]} LIKE '%{search_param}%'"
            data = curr.execute(search_query)
        else:
            gen_query = "SELECT * FROM technicians"
            data = curr.execute(gen_query)

        context = []

        for record in data:
            context_item = {
                "ssn":record[0],
                "first_name":record[1],
                "last_name":record[2],
                "gender": record[3],
                "phone_num": record[4],
                "street_address": record[5],
                "city": record[6],
                "country": record[7],
                "salary": record[8]
            }
            context.append(context_item)

    return render(request, 'technicians.html', {"context":context})

def get_technician_data(request, ssn):
    conn = oracledb.connect(
        user="system",
        password="anish",
        host="localhost",
        port="1521",
        service_name="XE"
    )

    curr = conn.cursor()

    query = f"SELECT * FROM technicians WHERE ssn = '{ssn}'"

    result = curr.execute(query)

    for record in result:
        technician_details = {
            "ssn":record[0],
            "first_name":record[1],
            "last_name":record[2],
            "gender": record[3],
            "phone_num": record[4],
            "street_address": record[5],
            "city": record[6],
            "country": record[7],
            "salary": record[8]
        }

    model_query = f"""
        SELECT * FROM models
        WHERE model_num IN (
            SELECT model_num FROM expertise
            WHERE ssn = '{technician_details["ssn"]}'
        )
    """

    result = curr.execute(model_query)

    model_details = []
    for record in result:
        model_item = {
            "model_num": record[0],
            "capacity": record[1],
            "weight": record[2]
        }
        model_details.append(model_item)

    tests_query = f"""
        SELECT tests.test_date, tests.test_num, tests.airplane_score, tests.maximum_score, tests.registration_num, airplanes.model_num
        FROM tests, airplanes
        WHERE tests.ssn = '{technician_details["ssn"]}'
            AND tests.registration_num = airplanes.registration_num
        ORDER BY tests.test_date DESC
    """

    result = curr.execute(tests_query)

    test_details = []
    counter = 1
    for record in result:
        test_item = {
            "serial_num": counter,
            "test_date":str(record[0].date()),
            "test_num":record[1],
            "airplane_score": record[2],
            "maximum_score": record[3],
            "registration_num": record[4],
            "model_num": record[5]
        }
        test_details.append(test_item)
        counter += 1

    print(tests_query)

    context = {
        "technician_details":technician_details,
        "model_details": model_details,
        "test_details":test_details
    }
    return render(request, 'technicianProfile.html', {"context": context})    

    

django_project/vimanam/templates/airplaneProfile.html
{% load tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% tailwind_preload_css %}
    {% tailwind_css %}
    <link rel="stylesheet" href="{% static 'fonts/anderson.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/inter.css' %}">
</head>
<body>
    {% block content%}
    <div id="main" class="font-inter">
        <div class="nav-bar top-12 absolute flex flex-row justify-center w-full">
            <div class="flex justify-start bg-pearl text-space-cadet z-10 rounded-3xl text-xs">
                <a class="flex flex-col justify-center p-4 hover:bg-space-cadet hover:text-cornsilk hover:rounded-3xl hover:ease-linear" href="{% url 'home:getContextData' %}">HOME</a>
                <a class="flex flex-col justify-center p-4 hover:bg-space-cadet hover:text-cornsilk hover:rounded-3xl hover:ease-linear" href="{% url 'airplanes:getContextData' %}">AIRPLANES</a>
                <a class="flex flex-col justify-center p-4 hover:bg-space-cadet hover:text-cornsilk hover:rounded-3xl hover:ease-linear" href="{% url 'models:getContextData' %}">MODELS</a>
                <a class="flex flex-col justify-center p-4 hover:bg-space-cadet hover:text-cornsilk hover:rounded-3xl hover:ease-linear" href="{% url 'technicians:getContextData' %}">TECHNICIANS</a>
                <a class="flex flex-col justify-center p-4 hover:bg-space-cadet hover:text-cornsilk hover:rounded-3xl hover:ease-linear" href="{% url 'tests:getContextData' %}">TESTS</a>
            </div>
        </div>

        <div class="bg-firebrick h-64 flex justify-left items-end">
            <div class="flex flex-col justify-left items-start mx-20">
                <h1 class="text-center text-5xl font-bold mb-5 font-anderson text-cornsilk">Airplane Profile</h1>
            </div>
        </div>

        <div class="grid grid-cols-12 grid-rows-7">
            <div class="col-start-1 col-end-6 row-start-1 row-end-2 text-left p-2 pb-5 m-8 ml-20 text-lg outline rounded-2xl">
                <div class="flex flex-col">
                    <p class="font-semibold text-center">Details</p>

                    <div class="grid grid-cols-2">
                        <p class="col-start-1 col-end-2 pl-2">Registration Number:</p>
                        <p class="col-start-2 col-end-3 pl-16">{{context.airplane_details.registration_num}}</p>
                    </div>

                    <div class="grid grid-cols-2">
                        <p class="col-start-1 col-end-2 pl-2">Model Number:</p>
                        <p class="col-start-2 col-end-3 pl-16">{{context.airplane_details.model_num}}</p>
                    </div>

                    <div class="grid grid-cols-2">
                        <p class="col-start-1 col-end-2 pl-2">Airline:</p>
                        <p class="col-start-2 col-end-3 pl-16">{{context.airplane_details.airline}}</p>
                    </div>
                </div>
            </div> 
            

            <div class="col-start-1 col-end-6 row-start-2 row-end-3 text-left p-2 pb-5 m-8 ml-20 text-lg outline rounded-2xl">
                <div class="flex flex-col gap-1">
                    <p class="font-semibold text-center">Model</p>
                
                    <div class="w-full flex flex-row justify-center h-48 p-2">
                        <img src="https://res.cloudinary.com/df0fmqsyt/database/models/{{context.model_details.model_num}}.jpg" class="object-cover h-full rounded-xl w-full">
                    </div>
                    

                    <div class="grid grid-cols-2">
                        <p class="col-start-1 col-end-2 pl-2">Model Number:</p>
                        <p class="col-start-2 col-end-3 pl-16">{{context.model_details.model_num}}</p>
                    </div>

                    <div class="grid grid-cols-2">
                        <p class="col-start-1 col-end-2 pl-2">Capacity:</p>
                        <p class="col-start-2 col-end-3 pl-16">{{context.model_details.capacity}}</p>
                    </div>

                    <div class="grid grid-cols-2">
                        <p class="col-start-1 col-end-2 pl-2">Weight:</p>
                        <p class="col-start-2 col-end-3 pl-16">{{context.model_details.weight}}</p>
                </div>
                </div>
            </div> 

            <div class="col-start-6 col-end-13 row-start-1 row-end-4 text-left p-2 pb-5 m-8 ml-10 mr-20 text-lg outline rounded-2xl">
                <p class="font-semibold text-center">Tests</p>

                <table class="w-full p-2">
                    <thead>
                        <th scope="col">S no.</th>
                        <th scope="col">Test Date</th>
                        <th scope="col">Test No.</th>
                        <th scope="col">Score Received</th>
                    </thead>

                    <tbody>
                        {% for test in context.tests_details %}
                        <tr>
                            <td>{{test.serial_num}}</td>
                            <td>{{test.test_date}}</td>
                            <td>{{test.test_num}}</td>
                            <td>{{test.airplane_score}} / {{test.maximum_score}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <h1 class="text-2xl text-center mt-8 mb-12 font-bold">Technicians</h1>

        <div class="flex flex-row flex-wrap justify-between gap-8 mx-20">
            {% for technician in context.technicians_details %}

            <div class="h-96 w-64 outline flex flex-col justify-start gap-5 rounded-2xl">
                <div class="w-full h-72 flex flex-row justify-center">
                    <img src="https://res.cloudinary.com/df0fmqsyt/database/technicians/{{technician.ssn}}.jpg" class="object-cover w-full h-full rounded-xl">
                </div>
                <div class="flex flex-col justify-center">
                    <p class="font-semibold text-center">{{technician.first_name}} {{technician.last_name}}</p>
                    <p class="font-light text-center">{{technician.ssn}}</p>
                </div>
            </div>
            
            {% endfor %}
        </div>

    </div>


    {% endblock %}
    <script src="{% static 'js/general.js' %}"></script>
</body>
</html

django_project/vimanam/templates/airplanes.html
{% load tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% tailwind_preload_css %}
    {% tailwind_css %}
    <link rel="stylesheet" href="{% static 'fonts/anderson.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/inter.css' %}">
</head>
<body style="overflow-x: hidden; width: 100%; height: 100%;">
    {% block content%}
    <div id="main" class="font-inter">
        <div class="nav-bar top-12 absolute flex flex-row justify-center w-full">
            <div class="flex justify-start bg-pearl text-space-cadet z-10 rounded-3xl text-xs">
                <a class="flex flex-col justify-center p-4 hover:bg-space-cadet hover:text-cornsilk hover:rounded-3xl hover:ease-linear" href="{% url 'home:getContextData' %}">HOME</a>
                <a class="flex flex-col justify-center p-4 hover:bg-space-cadet hover:text-cornsilk hover:rounded-3xl hover:ease-linear" href="#">AIRPLANES</a>
                <a class="flex flex-col justify-center p-4 hover:bg-space-cadet hover:text-cornsilk hover:rounded-3xl hover:ease-linear" href="{% url 'models:getContextData' %}">MODELS</a>
                <a class="flex flex-col justify-center p-4 hover:bg-space-cadet hover:text-cornsilk hover:rounded-3xl hover:ease-linear" href="{% url 'technicians:getContextData' %}">TECHNICIANS</a>
                <a class="flex flex-col justify-center p-4 hover:bg-space-cadet hover:text-cornsilk hover:rounded-3xl hover:ease-linear" href="{% url 'tests:getContextData' %}">TESTS</a>
            </div>
        </div>

        <div class="bg-yankees-blue h-64 flex justify-left items-end">
            <div class="flex flex-col justify-left items-start mx-20">
                <h1 class="text-center text-5xl mb-5 font-bold text-cornsilk font-anderson">Airplanes</h1>
            </div>
        </div>

        <div class="mx-20">
            <div class="w-full grid grid-cols-12 my-8">
                <div class="col-start-1 col-end-13">
                    <form class="grid grid-cols-12" action="{% url 'airplanes:getContextData' %}" method="get">
                        {% csrf_token %}
                        <input type="text" class="col-start-1 col-end-9 border-2 rounded-xl" name="s" placeholder="Search">
                        
                        <select name="f" id="form-select" class="col-start-9 col-end-11 mx-4 rounded-xl">
                            <option value="1">Reg. Number</option>
                            <option value="2">Model Number</option>
                            <option value="3">Airline</option>
                        </select>

                        <button type="submit" class="col-start-11 col-end-13 mx-4 border-2 rounded-xl">Search</button>
                    </form>
                </div>
                
                <div class="col-start-1 col-end-9 row-start-2 mt-10">
                    <table class="items-center bg-transparent w-full text-lg outline outline-pearl rounded-xl">
                        <thead>
                          <tr>
                            <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 uppercase py-3 border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                                Registration Number
                                        </th>
                          <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                                Model Number
                                        </th>
                           <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                                Airline
                                        </th>
                          </tr>
                        </thead>
                
                        <tbody>
                            {% if context %}
                                {% for context_item in context %}
                            <tr class="hover:bg-yankees-blue hover:text-cornsilk" data-href="/airplanes/d/{{context_item.registration_num}}">
                                <th class="font-semibold border-t-0 px-6 align-middle border-l-0 border-r-0 whitespace-nowrap p-4 text-left text-blueGray-700 border border-solid border-blueGray-100">
                                    {{context_item.registration_num}}
                                </th>
                                <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 whitespace-nowrap p-4 border border-solid border-blueGray-100">
                                    {{context_item.model_num}}
                                </td>
                                <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 whitespace-nowrap p-4 border border-solid border-blueGray-100">
                                    {{context_item.airline}}
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}
                                <p>No content found!</p>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
    
        </div>
        
    </div>
    
    {% endblock %}
    <script src="{% static 'js/general.js' %}"></script>
</body>
</html>

django_project/vimanam/templates/modelProfile.html
{% load tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% tailwind_preload_css %}
    {% tailwind_css %}
    <link rel="stylesheet" href="{% static 'fonts/anderson.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/inter.css' %}">
</head>
<body>
    {% block content%}
    <div id="main" class="font-inter">
        <div class="nav-bar top-12 absolute flex flex-row justify-center w-full">
            <div class="flex justify-start bg-pearl text-space-cadet z-10 rounded-3xl text-xs">
                <a class="flex flex-col justify-center p-4 hover:bg-space-cadet hover:text-cornsilk hover:rounded-3xl hover:ease-linear" href="{% url 'home:getContextData' %}">HOME</a>
                <a class="flex flex-col justify-center p-4 hover:bg-space-cadet hover:text-cornsilk hover:rounded-3xl hover:ease-linear" href="{% url 'airplanes:getContextData' %}">AIRPLANES</a>
                <a class="flex flex-col justify-center p-4 hover:bg-space-cadet hover:text-cornsilk hover:rounded-3xl hover:ease-linear" href="{% url 'models:getContextData' %}">MODELS</a>
                <a class="flex flex-col justify-center p-4 hover:bg-space-cadet hover:text-cornsilk hover:rounded-3xl hover:ease-linear" href="{% url 'technicians:getContextData' %}">TECHNICIANS</a>
                <a class="flex flex-col justify-center p-4 hover:bg-space-cadet hover:text-cornsilk hover:rounded-3xl hover:ease-linear" href="{% url 'tests:getContextData' %}">TESTS</a>
            </div>
        </div>

        <div class="bg-firebrick h-64 flex justify-left items-end">
            <div class="flex flex-col justify-left items-start mx-20">
                <h1 class="text-center text-5xl font-bold font-anderson mb-5 text-cornsilk">Models</h1>
            </div>
        </div>

        <div class="grid grid-cols-12 grid-rows-6">
            <div class="col-start-1 col-end-6 row-start-1 row-end-7 flex flex-row flex-wrap justify-center gap-8 ml-20 m-8">
                <div class="h-96 outline flex flex-col justify-start gap-1 rounded-2xl">
                    <div class="w-full flex flex-row justify-center h-72 p-2">
                        <img src="https://res.cloudinary.com/df0fmqsyt/database/models/{{context.model_details.model_num}}.jpg" class="object-cover h-full rounded-xl w-full">
                    </div>
                    <div class="flex flex-col justify-center">
                        <p class="font-semibold text-center">{{context.model_details.model_num}}</p>
                        <p class="font-light text-center">{{context.model_details.capacity}} Passengers.</p>
                        <p class="font-light text-center">{{context.model_details.weight}} Tons.</p>
                    </div>
                </div>
            </div>

            <div class="col-start-6 col-end-13 row-start-1 row-end-6 text-left p-2 pb-5 m-8 ml-10 mr-20 text-lg outline rounded-2xl">
                <p class="font-semibold text-center">Airplanes</p>

                <table class="w-full p-2">
                    <thead>
                        <th scope="col">S No.</th>
                        <th scope="col">Registration No.</th>
                        <th scope="col">Airline</th>
                    </thead>

                    <tbody>
                        {% for airplane in context.airplane_details %}
                        <tr>
                            <td>{{airplane.serial_num}}</td>
                            <td>{{airplane.registration_num}}</td>
                            <td>{{airplane.airline}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <h1 class="font-bold text-2xl my-12 text-center">Technicians</h1>
        <div class="flex flex-row flex-wrap justify-between gap-8 mx-20">
            {% for technician in context.technicians_details %}

            <div class="h-96 w-64 outline flex flex-col justify-start gap-5 rounded-2xl">
                <div class="w-full h-72 flex flex-row justify-center">
                    <img src="https://res.cloudinary.com/df0fmqsyt/database/technicians/{{technician.ssn}}.jpg" class="object-cover w-full h-full rounded-xl">
                </div>
                <div class="flex flex-col justify-center">
                    <p class="font-semibold text-center">{{technician.first_name}} {{technician.last_name}}</p>
                    <p class="font-light text-center">{{technician.ssn}}</p>
                </div>
            </div>
            
            {% endfor %}
        </div>

    </div>
    {% endblock %}
    <script src="{% static 'js/general.js' %}"></script>
</body>
</html>